imports:
  - { resource: services/behat/fields.yaml }

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  EzSystems\EzPlatformAdminUi\Behat\PageElement\DateAndTimePopup: ~

  EzSystems\EzPlatformAdminUi\Behat\PageElement\Notification: ~

  EzSystems\EzPlatformAdminUi\Behat\PageElement\Breadcrumb: ~

  EzSystems\EzPlatformAdminUi\Behat\PageElement\Dialog: ~

  EzSystems\EzPlatformAdminUi\Behat\PageElement\Pagination: ~

  EzSystems\EzPlatformAdminUi\Behat\PageElement\UniversalDiscoveryWidget: ~

  EzSystems\EzPlatformAdminUi\Behat\PageElement\ContentItemAdminPreview:
    arguments:
      $fieldTypeComponents: !tagged_iterator ezplatform.behat.admin_ui.field

  EzSystems\EzPlatformAdminUi\Behat\PageElement\DraftConflictDialog: ~

  EzSystems\EzPlatformAdminUi\Behat\PageElement\UpperMenu: ~

  EzSystems\EzPlatformAdminUi\Behat\PageElement\RightMenu: ~

  EzSystems\EzPlatformAdminUi\Behat\PageElement\UserNotificationPopup: ~

  EzSystems\EzPlatformAdminUi\Behat\PageElement\ContentTypePicker: ~

  EzSystems\EzPlatformAdminUi\Behat\PageElement\LanguagePicker: ~

  EzSystems\EzPlatformAdminUi\Behat\PageElement\SubItemsList: ~

  EzSystems\EzPlatformAdminUi\Behat\PageElement\LeftMenu: ~

  EzSystems\EzPlatformAdminUi\Behat\PageElement\TableNavigationTab: ~

  EzSystems\EzPlatformAdminUi\Behat\PageElement\Table\Table:
    shared: false

  EzSystems\EzPlatformAdminUi\Behat\PageElement\Table\TableFactory: ~

  EzSystems\EzPlatformAdminUi\Behat\PageElement\Table\SubitemsGrid: ~