services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  EzSystems\EzPlatformAdminUi\Behat\BrowserContext\AdminUpdateContext: ~

  EzSystems\EzPlatformAdminUi\Behat\BrowserContext\ContentViewContext: ~

  EzSystems\EzPlatformAdminUi\Behat\BrowserContext\ObjectStatesContext: ~

  EzSystems\EzPlatformAdminUi\Behat\BrowserContext\SystemInfoContext: ~

  EzSystems\EzPlatformAdminUi\Behat\BrowserContext\AdministrationContext: ~

  EzSystems\EzPlatformAdminUi\Behat\BrowserContext\DashboardContext: ~

  EzSystems\EzPlatformAdminUi\Behat\BrowserContext\RightMenuContext: ~

  EzSystems\EzPlatformAdminUi\Behat\BrowserContext\TrashContext: ~

  EzSystems\EzPlatformAdminUi\Behat\BrowserContext\ContentPreviewContext: ~

  EzSystems\EzPlatformAdminUi\Behat\BrowserContext\LeftMenuContext: ~

  EzSystems\EzPlatformAdminUi\Behat\BrowserContext\RolesContext: ~

  EzSystems\EzPlatformAdminUi\Behat\BrowserContext\UDWContext: ~

  EzSystems\EzPlatformAdminUi\Behat\BrowserContext\ContentTypeContext: ~

  EzSystems\EzPlatformAdminUi\Behat\BrowserContext\NavigationContext: ~

  EzSystems\EzPlatformAdminUi\Behat\BrowserContext\SearchContext: ~

  EzSystems\EzPlatformAdminUi\Behat\BrowserContext\UserNotificationContext: ~

  EzSystems\EzPlatformAdminUi\Behat\BrowserContext\ContentUpdateContext: ~

  EzSystems\EzPlatformAdminUi\Behat\BrowserContext\NotificationContext: ~

  EzSystems\EzPlatformAdminUi\Behat\BrowserContext\SectionsContext: ~

  EzSystems\EzPlatformAdminUi\Behat\BrowserContext\LanguageContext: ~
